#!/bin/bash
# refresh-secrets.sh
# Fetches all OpenClaw secrets from 1Password and writes ~/.openclaw/.secrets.env.
# Safe to run daily — idempotent, atomic write.
#
# Called by:
#   - ai.openclaw.secrets-refresh.plist (daily at 9am)
#   - ai.openclaw.secrets-watchdog.plist (on gateway auth failure)
#   - Manually: ~/.openclaw/refresh-secrets.sh && launchctl kickstart -k gui/$(id -u)/ai.openclaw.gateway

set -euo pipefail

OP="/opt/homebrew/bin/op"
JQ="/opt/homebrew/bin/jq"
OUT="$HOME/.openclaw/.secrets.env"
LOG="$HOME/.openclaw/logs/secrets-refresh.log"
GATEWAY_LABEL="ai.openclaw.gateway"

log() { echo "[$(date '+%Y-%m-%dT%H:%M:%S')] $*" | tee -a "$LOG" >&2; }

log "Fetching secrets from 1Password..."

ITEM_JSON=$("$OP" item get "OpenClawCredentials" --vault OpenClaw --format json)

_sf() {
  printf '%s' "$ITEM_JSON" | "$JQ" -r \
    --arg s "$1" --arg l "$2" \
    '.fields[] | select(.section.label==$s and .label==$l) | .value // empty'
}

ANTHROPIC_TOKEN=$(_sf "Anthropic" "me@joeblack.nyc oauth token")
DISCORD_TOKEN=$(_sf "Discord Bot" "bot token")
TELEGRAM_TOKEN=$(_sf "Telegram Bot" "password")
GATEWAY_TOKEN=$(_sf "OpenClaw" "gateway auth token")
SAG_KEY=$(_sf "SAG" "api key")
GOPLACES_KEY=$(_sf "Google Places" "api key")
GOOGLE_KEY=$(_sf "Google API" "api key")
ZAI_KEY=$(_sf "z.ai" "api key")
CODEX_TOKEN=$(_sf "Codex" "oauth token")

# Validate critical fields
for var_val in \
  "ANTHROPIC_TOKEN:$ANTHROPIC_TOKEN" \
  "DISCORD_TOKEN:$DISCORD_TOKEN" \
  "TELEGRAM_TOKEN:$TELEGRAM_TOKEN" \
  "GATEWAY_TOKEN:$GATEWAY_TOKEN" \
  "GOOGLE_KEY:$GOOGLE_KEY"; do
  name="${var_val%%:*}"; val="${var_val#*:}"
  if [ -z "$val" ]; then
    log "ERROR: $name resolved to empty — aborting"
    exit 1
  fi
done

# Check Codex JWT expiry (warn if within 2 days)
if [ -n "$CODEX_TOKEN" ]; then
  exp=$(echo "$CODEX_TOKEN" | python3 -c "
import sys, base64, json
t = sys.stdin.read().strip()
parts = t.split('.')
if len(parts) == 3:
    p = parts[1] + '=' * (4 - len(parts[1]) % 4)
    d = json.loads(base64.urlsafe_b64decode(p))
    print(d.get('exp', ''))
" 2>/dev/null || true)
  if [ -n "$exp" ]; then
    now=$(date +%s)
    days_left=$(( (exp - now) / 86400 ))
    if [ "$days_left" -le 2 ]; then
      log "WARNING: Codex OAuth token expires in ${days_left}d — renew at claude.ai/codex"
    else
      log "Codex token OK: ${days_left}d remaining"
    fi
  fi
fi

# Write atomically
TMPFILE=$(mktemp "$HOME/.openclaw/.secrets.env.XXXXXX")
chmod 600 "$TMPFILE"

cat > "$TMPFILE" <<EOF
# Auto-generated by refresh-secrets.sh — do not edit
# Regenerated: $(date '+%Y-%m-%dT%H:%M:%S')
export CLAUDE_OAUTH_TOKEN=${ANTHROPIC_TOKEN}
export ANTHROPIC_API_TOKEN=${ANTHROPIC_TOKEN}
export DISCORD_BOT_TOKEN=${DISCORD_TOKEN}
export TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}
export OPENCLAW_GATEWAY_TOKEN=${GATEWAY_TOKEN}
export SAG_API_KEY=${SAG_KEY}
export GOPLACES_API_KEY=${GOPLACES_KEY}
export GOOGLE_API_KEY=${GOOGLE_KEY}
export ZAI_API_KEY=${ZAI_KEY}
export OPENAI_OAUTH_TOKEN=${CODEX_TOKEN}
EOF

mv "$TMPFILE" "$OUT"
chmod 600 "$OUT"
log "Secrets written to $OUT"

# Restart gateway to pick up new secrets
if launchctl list "$GATEWAY_LABEL" > /dev/null 2>&1; then
  log "Restarting gateway..."
  launchctl kickstart -k "gui/$(id -u)/$GATEWAY_LABEL" 2>&1 | while read -r line; do log "$line"; done
  log "Gateway restarted"
fi
